management:
  endpoints.web.exposure.include: health,info,prometheus,metrics
  endpoint.health.show-details: always
server:
  tomcat:
    connection-timeout: 2s
logging:
  pattern.console: "%d %-5level [request=%X{requestId:-none} operation=%X{operationId:-none}] %logger - %msg%n"
