spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/fintech}
    username: ${DB_USER:study}
    password: ${DB_PASSWORD:study}
  flyway:
    locations: classpath:db/migration

server:
  error:
    include-message: always
