spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/data}
    username: ${DB_USER:study}
    password: ${DB_PASSWORD:study}
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
    hibernate.ddl-auto: validate

